config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#waitforit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :yarns, only: [:index, :show] do
    resources :favourites, only: [:new, :create]
    resources :chatrooms, only: [:new, :create, :show] do
      resources :messages, only: :create
    end

    member do 
      delete :favourites, to: "favourites#destroy"
    end
  end
  resources :users, only: :show
  resources :favourites, only: :destroy
  resources :gauge_swatches, only: [:new, :create, :show, :index] do
    collection do
      get :my_gauges
    end
  end
  resources :messages, only: :destroy
end

app/models/gauge_swatch.rb
class GaugeSwatch < ApplicationRecord
  has_one_attached :image_url

  has_many :yarn_gauge_swatches, dependent: :destroy
  has_many :yarns, through: :yarn_gauge_swatches
  belongs_to :user
end

app/controllers/gauge_swatches_controller.rb
class GaugeSwatchesController < ApplicationController
  def index
    @gauge_swatches = GaugeSwatch.all
  end

  def my_gauges
    @my_gauge = GaugeSwatch.where(user: current_user)
  end

  def new
    @yarn = Yarn.all
    @gauge_swatch = GaugeSwatch.new
  end

  def create
    @gauge = GaugeSwatch.new(gauge_swatches_params)
    @gauge.user = current_user
    @gauge.yarns << Yarn.find(params[:Yarn]) if params[:Yarn].present?
    @gauge.yarns << Yarn.find(params[:Yarn2]) if params[:Yarn2].present?
    @gauge.yarns << Yarn.find(params[:Yarn3]) if params[:Yarn3].present?

    if @gauge.save
      redirect_to gauge_swatch_path(@gauge)
    else
      render new
    end
  end

  def show
    @gauge = GaugeSwatch.find(params[:id])
  end

  private

  def gauge_swatches_params
    params.require(:gauge_swatch).permit(:image_url, :gauge, :needles)
  end
end

app/views/gauge_swatches/index.html.erb
<h1 id="h1-gs">Gauge Swatches</h1>

<div class="gauge-instructions">
  Keep track of your test swatches online, by saving it's <strong>picture</strong>, <strong>yarn</strong> combination, <strong>gauge</strong> and <strong>needles</strong>.
<br>
  That will help you save space at home and get that yarn used for beautiful scrap projects instead.
<br>
<br>
  Remember to <strong>wash</strong> your swatch before storing it's data.

</div>


<div class="buttons-gs-all">
  <%= link_to "Create a Gauge Swatch", new_gauge_swatch_path,  {:style=>'width:250px;', class: 'btn btn-primary'}  %>
  <%= link_to "See my Gauge Swatches", my_gauges_gauge_swatches_path, {:style=>'width:250px;', class: 'btn btn-primary'}  %>
</div>
<div class="grid-container" id="gauge-container">
  <% @gauge_swatches.each do |gauge_swatch| %>
  <div class="card-product">
    <%= cl_image_tag gauge_swatch.image_url.key, height: 300, width: 400, crop: :fill %>
    <div class="card-product-infos">
      <p><strong> Gauge: </strong><%= gauge_swatch.gauge %></p>
      <p><strong> Needle: </strong><%= gauge_swatch.needles %></p>
      <p><strong>Author: </strong><%= gauge_swatch.user.username %></p>
      <p><strong>Yarns used:</strong></p>
      <% gauge_swatch.yarns.each do |t| %>
        <p><%= t.name %></p>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/gauge_swatches/my_gauges.html.erb
<h1 id="h1-gs">My gauges swatches</h1>

<div class="grid-container">
  <% unless (@my_gauge == []) %>
      <% @my_gauge.each do |gauge_swatch| %>
          <div class="card-product">
            <%= cl_image_tag gauge_swatch.image_url.key, height: 300, width: 400, crop: :fill %>
            <div class="card-product-infos">
              <p>Gauge: <%= gauge_swatch.gauge %></p>
              <p>Needle: <%= gauge_swatch.needles %></p>
              <%= link_to "Open this swatch", gauge_swatch_path(gauge_swatch) %>
            </div>
          </div>
      <% end %>
  <% end %>
</div>

app/views/gauge_swatches/new.html.erb
<br>
<h1 id="title-gs">Add your swatch!</h1>
<div class="gauge-instructions">
  Keep track of your test swatches online, by saving it's <strong>picture</strong>, <strong>yarn</strong> combination, <strong>gauge</strong> and <strong>needles</strong>.
<br>
  That will help you save space at home and get that yarn used for beautiful scrap projects instead.
<br>
<br>
  Remember to <strong>wash</strong> your swatch before storing it's data.

</div>
<div class="container-new-gs">
  <div class="form-gauge-swatch">
  <%= form_for(@gauge_swatch) do |f| %>
    <div class="instructions">
      <p>Upload your image, add gauge and needles information:</p>
    </div>
    <div class="form-img-gauge-needle">
      <p class="label-gs"><%= f.label "Image Upload:" %></p>
      <div class="image-upload">
       <label for="file-input">
         <span id="button-upload">Select</span >
       </label>

       <%= f.file_field :image_url, id:"file-input" %>
      </div>

        <p class="label-gs"><%= f.label "Gauge:" %></p>
        <p class="field-gs"><%= f.text_field :gauge, style: "width: 80px" %> sts. per 10 cm</p>
        <p class="label-gs"> <%= f.label "Needles:" %></p>
        <p class="field-gs"><%= f.text_field :needles, style: "width: 80px" %></p> mm.

    </div>

    <div class="instructions">
      <p>Yarn(s) being used:</p>
    </div>

    <div class="form-yarn-gs">
      <% options = options_from_collection_for_select(@yarn, 'id', 'name')%>
      <%= select_tag 'Yarn', options_for_select(options), {:include_blank => 'Select an yarn', class: 'option-gs-field'} %>
      <% options = options_from_collection_for_select(@yarn, 'id', 'name') %>
      <%= select_tag 'Yarn2', options_for_select(options), {:include_blank => 'Select another yarn', class: 'option-gs-field'} %>
      <% options = options_from_collection_for_select(@yarn, 'id', 'name') %>
      <%= select_tag 'Yarn3', options_for_select(options), {:include_blank => 'Select another yarn', class: 'option-gs-field'} %>
    </div>


    <div class="button-gs">  <%= f.submit "Create Swatch", style: "background-color: #8ac6d1;" %> </div>
  <% end %>
  </div>
</div>

app/views/gauge_swatches/show.html.erb
<h1 id="h1-gs">Your Swatch Info</h1>

<div class="center">
  <div class="buttons-gs-all">
  <%= link_to "Create a Gauge Swatch", new_gauge_swatch_path,  {:style=>'width:250px;', class: 'btn btn-primary'}  %>
  <%= link_to "See my Gauges Swatches", my_gauges_gauge_swatches_path, {:style=>'width:250px;', class: 'btn btn-primary'}  %>
</div>
</div>



<div class="container-show-gs">
  <div class="show-card-gs">
    <div class="show-img-gs">
      <%= cl_image_tag @gauge.image_url.key, height: 300, width: 400, crop: :fill %>
    </div>
    <div class="show-card-infos-gs">
      <h2>Information:</h2>
      <p><strong>Gauge: </strong><%= @gauge.gauge %></p>
      <p><strong>Needles: </strong><%= @gauge.needles %></p>
      <p><strong>User: </strong><%= @gauge.user.username %></p>

      <h2>Yarns used in this swatch:</h2>
      <% @gauge.yarns.each do |t| %>
        <p><%= t.name %> by <%= t.brand.name %></p>
      <% end %>
    </div>
  </div>
</div>