config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#waitforit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :yarns, only: [:index, :show] do
    resources :favourites, only: [:new, :create]
    resources :chatrooms, only: [:new, :create, :show] do
      resources :messages, only: :create
    end

    member do 
      delete :favourites, to: "favourites#destroy"
    end
  end
  resources :users, only: :show
  resources :favourites, only: :destroy
  resources :gauge_swatches, only: [:new, :create, :show, :index] do
    collection do
      get :my_gauges
    end
  end
  resources :messages, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :yarns
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :yarn
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :yarn
end

app/models/gauge_swatch.rb
class GaugeSwatch < ApplicationRecord
  has_one_attached :image_url

  has_many :yarn_gauge_swatches, dependent: :destroy
  has_many :yarns, through: :yarn_gauge_swatches
  belongs_to :user
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :yarns, through: :yarn_materials
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favourites, dependent: :destroy
  has_many :gauge_swatches
end

app/models/yarn.rb
class Yarn < ApplicationRecord
  belongs_to :brand
  has_many :yarn_materials
  has_many :materials, through: :yarn_materials

  has_many :yarn_gauge_swatches, dependent: :destroy
  has_many :gauge_swatches, through: :yarn_gauge_swatches

  include PgSearch::Model
  pg_search_scope :search_by_name,
  against: [ :name ],
  using: {
    tsearch: { prefix: true }
  }
  pg_search_scope :search_by_weight,
  against: [ :weight ],
  using: {
    tsearch: { prefix: true }
  }
  pg_search_scope :search_by_needles,
  against: [ :needles ],
  using: {
    tsearch: { prefix: true }
  }
  pg_search_scope :search_by_gauge,
  against: [ :gauge ],
  using: {
    tsearch: { prefix: true }
  }

  pg_search_scope :search_by_brand,
    associated_against: {
      brand: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
  }
end

app/models/yarn_gauge_swatch.rb
class YarnGaugeSwatch < ApplicationRecord
  belongs_to :gauge_swatch, dependent: :destroy
  belongs_to :yarn
end

app/models/yarn_material.rb
class YarnMaterial < ApplicationRecord
  belongs_to :material, dependent: :destroy
  belongs_to :yarn
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def default_url_options
    { host: ENV["www.yarnalt.com"] || "localhost:3000" }
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    # chatroom igual ao yarn id
    @chatroom = Chatroom.find(params[:id])
    @yarn = @chatroom.yarn
    @message = Message.new
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @yarn = Yarn.find(params[:yarn_id])
    new
    @chatroom.yarn = @yarn
    @chatroom.name = @yarn.name

    if @chatroom.save
      redirect_back(fallback_location: root_path)
    else
      render :new
    end
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
  end

  def new
    @favourite = Favourite.new
  end

  def create
    @yarn = Yarn.find(params[:yarn_id])
    @favourite = Favourite.new
    @favourite.user = current_user
    @favourite.yarn = @yarn

    if @favourite.save
      # redirect_to yarn_path(@yarn)
      render json: :ok
    else
      # render :new
    end
  end

  def destroy
    @favourite = current_user.favourites.find_by(yarn_id: params[:id])
    @favourite.destroy
    
    render json: :ok
  end

  private

  def favourite_params
    params.require(:favourite).permit(:yarn_id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      # send to the channel

      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "shared/message", locals: { message: @message })
      )
      # redirect_back(fallback_location: root_path)
        redirect_to chatroom_path(@chatroom, anchor: "message-#{message.id}")
    else
      render "chatrooms/show"
    end
  end

  def destroy
    message = Message.find(params[:id])
    chatroom = message.chatroom
    yarn = chatroom.yarn
    message.destroy
    # authorize @message
    redirect_to yarn_chatroom_path(yarn, chatroom)
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :waitforit ]

  def home
    @yarns = Yarn.all.order("RANDOM()")
    # @materials = Material.all
    # @brands = Brand.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/yarns_controller.rb
class YarnsController < ApplicationController

  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @option = params[:option_id]
    if params[:query] && @option == '1'
      @yarns = Yarn.search_by_name(params[:query])
    elsif params[:query] && @option == '2'
      @yarns = Yarn.search_by_weight(params[:query])
    elsif params[:query] && @option == '3'
      @yarns = Yarn.search_by_needles(params[:query])
    elsif params[:query] && @option == '4'
      @yarns = Yarn.search_by_gauge(params[:query])
    elsif params[:query] && @option == '5'
      @yarns = Yarn.search_by_brand(params[:query])
    else
      @yarns = Yarn.all.order("RANDOM()")
    end
  end

  def show
    @favourite = Favourite.where(user: current_user, yarn: params[:id])
    @yarn = Yarn.find(params[:id])
    @chatroom = Chatroom.where(yarn: @yarn)
    @yarn_equivalents = Yarn.where(gauge: @yarn.gauge).where.not(id: @yarn.id).order("RANDOM()")

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end
  
    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # little twist to make it work equally with an asset or a url
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YarnAlt - Find yarn alternatives to your projects</title>

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
<!-- <br> -->
    <%= render 'shared/footer' %>
  </body>

</html>

app/views/pages/home.html.erb
<script src="https://kit.fontawesome.com/940a81dcf7.js" crossorigin="anonymous"></script>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dzuoumhdx/image/upload/v1621551052/knit_pool_iy433n.jpg);">
<!--   The other image, in case we want that
  https://res.cloudinary.com/dzuoumhdx/image/upload/v1620813457/swatch_img_netfll.jpg -->
  <div class="container">
    <h1><strong>YarnAlt</strong></h1>
    <p>Find yarn alternatives to your projects</p>
  </div>
</div>

<div class="instructions">
  <p>Search by yarn <strong>name</strong>, <strong>brand</strong>, <strong>weight</strong>,
    <strong>needles</strong> suggested or <strong>gauge</strong> and find the perfect match for your project.</p>
</div>

<%= render 'shared/search' %>

<div class="grid-container">
  <% @yarns.limit(6).each do |yarn| %>
    <%= render 'shared/yarn', yarn: yarn %>
  <% end %>
</div>

app/views/pages/waitforit.html.erb
<script src="https://kit.fontawesome.com/940a81dcf7.js" crossorigin="anonymous"></script>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dzuoumhdx/image/upload/v1621551052/knit_pool_iy433n.jpg);">
  <div class="container">
    <h1><strong>YarnAlt</strong></h1>
    <p>Find yarn alternatives to your projects</p>
  </div>
</div>

<div class="waitforit-text">
  <p><strong>HI!</strong> Thanks for dropping by. <br>
  This web app was the proud outcome of a Full Stack Web Development bootcamp we attended <strong>@ Le Wagon</strong>. <br>
  We want to redo it and make it a much better experience.<br>
  Hopefully a beta version will come up soon. <br>

  If you would like to show some support, contact us at <br>

  <strong>H I  Y A R N A L T . C O M</strong><br>
<!--   (But if you would still like to see what we accomplished during the bootcamp, please click  <%= link_to "here.", yarns_path%>)
<br> -->
<br>
</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer" id="footer">
    <div class="footer-links">
      <a href="https://www.instagram.com/yarnalt/" target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/loveyarnalt/" target="_blank"><i class="fab fa-facebook"></i></a>
      <a href="https://twitter.com/YarnAlt" target="_blank"><i class="fab fa-twitter"></i></a>
    </div>
    <div class="footer-info">
<!--   This app is proudly presented by Lorena, Thiago and Mariana - LeWagon Brasil Batch #536 -->
Good things come to those who wait.
    </div>
  </div>
</footer>

app/views/shared/_message.html.erb
<div class="message-container" id="message-<%= message.id %>">
      <i class="author">
        <span><%= message.user.username %></span>
        <% date_message = message.created_at - 3*60*60 %>
        <small><%= date_message.strftime("%a %b %e at %l:%M%p") %></small>

        <% if @message.user != current_user%>
          <%= link_to "Delete", message_path(message), method: :delete, data: { confirm: "You are about to delete it!" }%>
        <% end %>

      </i>
      <p class="message-content"><%= message.content %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <h1>YarnAlt</h1>
    <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
          <%= link_to "Home", yarns_path, class: "nav-link" %>
        </li> -->
        <div class="logged-nav">
          <li class="nav-item"> You are logged as <%= current_user.username %> </li>
        </div>
        <li class="nav-item menu-info dropdown">
          <%= image_tag "https://res.cloudinary.com/dzuoumhdx/image/upload/v1622306054/menu_hpdstu.png", class: "nav-menu dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Gauge Swatches", gauge_swatches_path, class: "dropdown-item"  %>
            <%= link_to "My favourites", user_path(current_user.id), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
<!--           <%= link_to "Login", new_user_session_path, class: "nav-link" %> -->
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search">
  <%= form_tag yarns_path, method: :get, class:"form-inline" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a yarn"
  %>
  <%= select_tag(:option_id, options_for_select([['Yarn Name', 1], ['Weight', 2],
  ['Needles', 3], ['Gauge', 4], ['Brands', 5]]), class: "form-control") %>

  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
</div>

app/views/shared/_searchform.html.erb
<div>
  <%= form_tag yarns_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a yarn"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
</div>

app/views/shared/_yarn.html.erb
<div class="card-product">

    <img src="<%= yarn.image_url.present? ? yarn.image_url : 'https://res.cloudinary.com/dzuoumhdx/image/upload/v1621985362/yarn_xlqcff.jpg' %>" />

    <div class="card-product-infos">
      <h2><%= link_to truncate(yarn.name, :length => 20),  yarn_path(yarn) %></h2>
      <h3><%= yarn.brand.name %></h3>
      <p><strong>Weight: </strong> <%= yarn.weight.present? ? yarn.weight : "Unknown" %></p>
      <p><strong>Gauge: </strong> <%= yarn.gauge.present? ? yarn.gauge : "Unknown" %></p>
      <p><strong>Fiber: </strong> <%= yarn.materials[0]&.fiber_type %> <%= yarn.materials[0]&.percentage %>% </p>
      <p><strong>Needles: </strong> <%= yarn.needles %>mm</p>

      <div class="moreinfo" >
        <%= link_to "More info", yarn_path(yarn) %>
        <div class="fav-button">
          <% if current_user %>
            <% @fav = current_user.favourites.where(yarn_id: yarn.id) %>
          <% else %>
            <% @fav = [] %>
          <% end %>
           <%# <% unless @fav == [] %>
          <% if @fav == [] %>

            <%= link_to favourites_yarn_path(yarn), method: :delete, class: 'red-heart', id: 'red-heart', remote: true, style: 'display: none' do %>
              <i class="fas fa-heart"></i>
            <% end %>
            <%= link_to yarn_favourites_path(yarn), method: :post, class: 'gray-heart', id: 'gray-heart', remote: true do %>
              <i class="fas fa-heart"></i>
            <% end %>

          <% else %>

            <%= link_to favourites_yarn_path(yarn), method: :delete, class: 'red-heart', id: 'red-heart', remote: true do %>
              <i class="fas fa-heart"></i>

            <% end %>
            <%= link_to yarn_favourites_path(yarn), method: :post, class: 'gray-heart', id: 'gray-heart', remote: true, style: 'display: none' do %>
              <i class="fas fa-heart"></i>
            <% end %>

          <% end %>
        </div>
      </div>

    </div>


</div>

app/views/shared/_yarn_chatroom.html.erb
<div class="card-product-chatroom">

    <img src="<%= yarn.image_url.present? ? yarn.image_url : 'https://res.cloudinary.com/dzuoumhdx/image/upload/v1621985362/yarn_xlqcff.jpg' %>" />

    <div class="card-product-infos">
      <h2><%= link_to truncate(yarn.name, :length => 20),  yarn_path(yarn) %></h2>
      <h3><%= yarn.brand.name %></h3>
      <p><strong>Weight: </strong> <%= yarn.weight.present? ? yarn.weight : "Unknown" %></p>
      <p><strong>Gauge: </strong> <%= yarn.gauge.present? ? yarn.gauge : "Unknown" %></p>
      <p><strong>Fiber: </strong> <%= yarn.materials[0].fiber_type %> <%= yarn.materials[0].percentage %>% </p>
      <p><strong>Needles: </strong> <%= yarn.needles %>mm</p>

      <div class="moreinfo" >
        <%= link_to "More info", yarn_path(yarn) %>
        <div class="fav-button">
          <% if current_user %>
            <% @fav = current_user.favourites.where(yarn_id: yarn.id) %>
          <% else %>
            <% @fav = [] %>
          <% end %>
           <%# <% unless @fav == [] %>
          <% if @fav == [] %>

            <%= link_to favourites_yarn_path(yarn), method: :delete, class: 'red-heart', id: 'red-heart', remote: true, style: 'display: none' do %>
              <i class="fas fa-heart"></i>
            <% end %>
            <%= link_to yarn_favourites_path(yarn), method: :post, class: 'gray-heart', id: 'gray-heart', remote: true do %>
              <i class="fas fa-heart"></i>
            <% end %>

          <% else %>

            <%= link_to favourites_yarn_path(yarn), method: :delete, class: 'red-heart', id: 'red-heart', remote: true do %>
              <i class="fas fa-heart"></i>

            <% end %>
            <%= link_to yarn_favourites_path(yarn), method: :post, class: 'gray-heart', id: 'gray-heart', remote: true, style: 'display: none' do %>
              <i class="fas fa-heart"></i>
            <% end %>

          <% end %>
        </div>
      </div>

    </div>


</div>