config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#waitforit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :yarns, only: [:index, :show] do
    resources :favourites, only: [:new, :create]
    resources :chatrooms, only: [:new, :create, :show] do
      resources :messages, only: :create
    end

    member do 
      delete :favourites, to: "favourites#destroy"
    end
  end
  resources :users, only: :show
  resources :favourites, only: :destroy
  resources :gauge_swatches, only: [:new, :create, :show, :index] do
    collection do
      get :my_gauges
    end
  end
  resources :messages, only: :destroy
end

app/models/yarn.rb
class Yarn < ApplicationRecord
  belongs_to :brand
  has_many :yarn_materials
  has_many :materials, through: :yarn_materials

  has_many :yarn_gauge_swatches, dependent: :destroy
  has_many :gauge_swatches, through: :yarn_gauge_swatches

  include PgSearch::Model
  pg_search_scope :search_by_name,
  against: [ :name ],
  using: {
    tsearch: { prefix: true }
  }
  pg_search_scope :search_by_weight,
  against: [ :weight ],
  using: {
    tsearch: { prefix: true }
  }
  pg_search_scope :search_by_needles,
  against: [ :needles ],
  using: {
    tsearch: { prefix: true }
  }
  pg_search_scope :search_by_gauge,
  against: [ :gauge ],
  using: {
    tsearch: { prefix: true }
  }

  pg_search_scope :search_by_brand,
    associated_against: {
      brand: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
  }
end

app/controllers/yarns_controller.rb
class YarnsController < ApplicationController

  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @option = params[:option_id]
    if params[:query] && @option == '1'
      @yarns = Yarn.search_by_name(params[:query])
    elsif params[:query] && @option == '2'
      @yarns = Yarn.search_by_weight(params[:query])
    elsif params[:query] && @option == '3'
      @yarns = Yarn.search_by_needles(params[:query])
    elsif params[:query] && @option == '4'
      @yarns = Yarn.search_by_gauge(params[:query])
    elsif params[:query] && @option == '5'
      @yarns = Yarn.search_by_brand(params[:query])
    else
      @yarns = Yarn.all.order("RANDOM()")
    end
  end

  def show
    @favourite = Favourite.where(user: current_user, yarn: params[:id])
    @yarn = Yarn.find(params[:id])
    @chatroom = Chatroom.where(yarn: @yarn)
    @yarn_equivalents = Yarn.where(gauge: @yarn.gauge).where.not(id: @yarn.id).order("RANDOM()")

  end
end

app/views/yarns/index.html.erb
<%= render 'shared/search' %>

<div class="grid-container">
  <% @yarns.limit(27).each do |yarn| %>
    <%= render 'shared/yarn', yarn: yarn %>
  <% end %>

</div>

app/views/yarns/show.html.erb
<div class="container d-flex justify-content-around mt-4">

  <div class="show-card">

    <div class="show-img">
      <img src="<%= @yarn.image_url.present? ? @yarn.image_url : 'https://res.cloudinary.com/dzuoumhdx/image/upload/v1621985362/yarn_xlqcff.jpg' %>" />
    </div>

    <div class="show-info-fav">
      <div class="show-card-infos">
        <h2><%= @yarn.name %></h2>

        <h3><%= @yarn.brand.name %></h3>
        <p><strong>Weight: </strong> <%= @yarn.weight %></p>
        <p><strong>Gauge: </strong> <%= @yarn.gauge %> sts</p>
        <p><strong>Fiber: </strong> <% @yarn.materials.each do |material| %>
        <%= material.percentage %>% <%= material.fiber_type %>
        <% end %>

        </p>
        <p><strong>Needles: </strong> <%= @yarn.needles %>mm</p>
        <p><strong>Availability:  </strong><%= @yarn.brand.location %> </p>
        <% if @yarn.discontinued == true %>
          <p>*This yarn has been discontinued.</p>
        <% end %>
      </div>

      <div class="fav-chat-buttons">
        <div class="fav-button-show">

          <% if current_user %>
            <% @fav = current_user.favourites.where(yarn_id: @yarn.id) %>
          <% else %>
            <% @fav = [] %>
          <% end %>

       <%# <% unless @fav == [] %> 
       <% if @fav == [] %>
          <%= link_to favourites_yarn_path(@yarn), method: :delete, class: 'red-heart', id: 'red-heart', remote: true, style: 'display: none' do %>
            <i class="fas fa-heart"></i>
          <% end %>
          <%= link_to yarn_favourites_path(@yarn), method: :post, class: 'gray-heart', id: 'gray-heart', remote: true do %>
            <i class="fas fa-heart"></i>
          <% end %>
        
        <% else %>

          <%= link_to favourites_yarn_path(@yarn), method: :delete, class: 'red-heart', id: 'red-heart', remote: true do %>
            <i class="fas fa-heart"></i>
          <% end %>
          <%= link_to yarn_favourites_path(@yarn), method: :post, class: 'gray-heart', id: 'gray-heart', remote: true, style: 'display: none' do %>
            <i class="fas fa-heart"></i>
          <% end %>

        <% end %>

        <%# <% end %> 
        
        </div>

        <div class="chat-button">
          <% if @chatroom[0].nil? %>
            <%= link_to 'Create Help Chat', yarn_chatrooms_path(@yarn), method: :post, class: 'btn btn-primary' %>
          <% else %>
            <%= link_to 'Go to Help Chat', yarn_chatroom_path(yarn_id: @chatroom[0].yarn_id, id: @chatroom[0].id), method: :get, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="yarn-list">

    <div class="showtitle">
      <h3>Equivalent Yarns</h3>
   </div>

   <% @yarn_equivalents.each do |yarn| %>
      <%= render 'shared/yarn', yarn: yarn %>
    <% end %>

  </div>

 </div>